apps/demand/urls.py
from django.urls import path

from . import views


app_name = "demand"

urlpatterns = [
    path(
        route="",
        view=views.HomeView.as_view(),
        name="home"
    )
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        route='admin/', 
        view=admin.site.urls
    ),
    path(
        route="",
        view=include("demand.urls", namespace="demand")
    )
]

apps/demand/models.py
from django.db import models


class DemandTechnology(models.Model):
    name = models.CharField(max_length=100, unique=True)
    count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name.title()
    
    class Meta:
        verbose_name_plural = "Demand Technologies"
        
    def save(self, *args, **kwargs):
        # to avoid having typos for names, like back-end instead of backend
        self.name.replace("-", "").strip().lower()
        if self.name.isascii():
            return super().save(*args, **kwargs)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, 
                                        PermissionsMixin, 
                                        UserManager)


class UserModel(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50, 
                                unique=True,
                                db_index=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    email = models.EmailField(blank=True, 
                              null=True, 
                              unique=True)
    
    objects = UserManager()
    
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["first_name", "last_name"]
    
    @property
    def name(self):
        return f"{self.first_name.title()} {self.last_name.title()}"
    
    def __str__(self):
        return f"{self.name} - @{self.username}"

apps/demand/views.py
import json
from django.views import View
from django.db.models import Sum, Avg
from django.shortcuts import render

from .models import DemandTechnology


class HomeView(View):
    template_name = "demands/index.html"
    
    def get(self, *args):
        tech_data = (
            DemandTechnology
            .objects
            .all()
            .order_by("-count")[:20]
            .values("name", "count")
        )
        others_count = 0
        if DemandTechnology.objects.count() > 20:
            others_count = (
                DemandTechnology
                .objects
                .all()[20:]
                .aggregate(s=Sum("count"))["s"]
            )
            
        chart_data = {
            i["name"]: i["count"] for i in tech_data.iterator()
        } | {"others": others_count} if others_count > 0 else {}
        
        avg_count = DemandTechnology.objects.aggregate(a=Avg("count"))["a"] or 0
        
        context = {
            "chart_data": chart_data,
            "data": (
                DemandTechnology
                .objects
                .filter(count__gt=avg_count)
                .order_by("-count")
                .values("name", "count")
            )
        }
        return render(self.request, self.template_name, context)

apps/users/views.py
from django.shortcuts import render

# Create your views here.

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"
    />
    <link
        href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.css"
        rel="stylesheet"
    />
    {% include 'includes/_scripts.html' %}
    <style>
        body {
            min-height: 100vh
        }
    </style>
    {% block style %}{% endblock %}
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body class="flex flex-col justify-between items-center gap-5 max-h-full w-full">
    {% include 'includes/_navbar.html' %}
    <main class="">
        {% block content %}{% endblock %}
    </main>
    {% include 'includes/_footer.html' %}
</body>
</html>

templates/demands/index.html
{% extends '_base.html' %}

{% block title %}Homepage{% endblock %}

{% block style %}
<style>
    th, td {
        border: .2rem dashed black;
        padding: .5rem
    }
</style>
{% endblock %}

{% block content %}
<section class="grid grid-cols-1 sm:grid-cols-2 w-full h-full gap-5">
        <div class="w-full my-auto self-center">
            <canvas id="tech_pie_chart"></canvas>
        </div>
        <div class="h-screen overflow-y-auto p-4 w-full">
            <table>
                <thead>
                    <tr>
                        <th>Row</th>
                        <th>Name</th>
                        <th>Count</th>
                    </tr>
                </thead>
                <tbody>
                    {% for d in data %}
                        <tr class="text-center font-sans">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ d.name }}</td>
                            <td>{{ d.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
</section>
<script>
const labels = `{{ chart_data.keys|join:','|safe|default:'' }}`.split(",")
const values = `{{ chart_data.values|join:','|safe|default:'' }}`.split(",")
const chartElem = document.getElementById("tech_pie_chart")
const chart = new Chart(chartElem, {
    type: 'doughnut',
    data: {
        datasets: [{
            data: values
        }],
        labels: labels,
    },
    options: {
        plugins: {
            legend: {
                display: false
            }
        }
    }
})
</script>
{% endblock %}

templates/includes/_footer.html
<footer class="flex flex-col mb-3">
    <div class="flex justify-center gap-4">
        <a href="https://telegram.me/RobSaman">
            <i class="fa fab fa-telegram text-4xl text-blue-500"></i>
        </a>
        <a href="https://linkedin.com/in/saman-zand-h">
            <i class="fa fab fa-linkedin text-4xl text-blue-700" style="opacity: 80%"></i>
        </a>
        <a href="https://github.com/saman-zand-h">
            <i class="fa fab fa-github text-4xl gray-900"></i>
        </a>
    </div>
    <div class="flex justify-center font-semibold text-xs">
        Copyright &copy; 2023
    </div>
</footer>

templates/includes/_navbar.html
<nav class="py-4 px-5 bg-gray-900 text-white w-full">
    <ul class="flex justify-start text-xl">
        <li>
            <a href="{% url 'demand:home' %}">
                Home
            </a>
        </li>
    </ul>
</nav>

templates/includes/_scripts.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>